### ISSUE TITLE
Add Subresource Integrity (SRI) to JS files

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-blog#115]
To improve the security of the files we serve from the CDN, let's add Subresource Integrity (SRI) to our JS files. Looks like there is a Gatsby plugin to help us out: https://github.com/ovhemert/gatsby-plugin-sri

To learn more about SRI: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by ch264** [comment]
yep, this plugin works on build only. PR is in, 
<img width="1120" alt="Screen Shot 2020-03-13 at 12 04 45 PM" src="https://user-images.githubusercontent.com/36343528/76651975-d7adb380-6522-11ea-87fa-374736bab18a.png">
