### ISSUE TITLE
Author's posts view: dates all showing today

### ISSUE THREAD

**Issue by mclausaudio** [postmanlabs/postman-blog#142]
Just noticed that when viewing a specific authors list of posts, all the dates are the same (today).  @ch264 I know you were working with moment but if you'd like me to take a look just lmk.  Thanks!

![screencapture-localhost-9000-joyce-page-1-2020-03-12-11_09_08](https://user-images.githubusercontent.com/14118422/76553829-fabc6280-6451-11ea-81f1-19b049ac0487.png)

**Comment by ch264** [comment]
yes, I am looking into this and we forgot to call date in the graphql call

**Comment by ch264** [comment]
PR is in
