### ISSUE TITLE
Algolia: bring back results only from Blog 

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-blog#163]
comment out LC index
switch Algolia keys?

**Comment by ch264** [comment]
@tristandenyer can we clarify if we are going to launch with both indexes results or just blog results?

**Comment by tristandenyer** [comment]
Day 1 of launch we can do just the blog results. I am hoping we can fast-follow with federated Blog + LC results (which needs design).

**Comment by ch264** [comment]
PR is in
