### ISSUE TITLE
Just-comments

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-blog#166]
sign up for license in order to use just-comments

**Comment by ch264** [comment]
@tristandenyer can we proceed with signing up for just-comments?

**Comment by ch264** [comment]
Hold off on this ticket, await final decision on comments

**Comment by ch264** [comment]
@tristandenyer do we have an update on JustComments subscription?

**Comment by tristandenyer** [comment]
@ch264 I have the approval, will purchase tomorrow.

**Comment by ch264** [comment]
justComments shutting down. 

look for alternative

**Comment by ch264** [comment]
build our own
