### ISSUE TITLE
Refactor EntryMeta.js

### ISSUE THREAD

**Issue by mclausaudio** [postmanlabs/postman-blog#19]
EntryMeta component is tarting to grow.  It currently handles parsing through and displaying a given posts 'tags' and 'categories'.  The logic for both is pretty much the same so we can probably break that into a separate component.

**Comment by mclausaudio** [comment]
This refactor will be dependent on if we decide to go with multiple 'categories'.  If more than 1 category, then the logic is the same and we can probably break it out into another component.  If it's a single one, the logic is different.

**Comment by ch264** [comment]
EntryMeta has been refactored and categories and tags are now in a seperate component called Tags.jsx.
