### ISSUE TITLE
make footer same as WWWv2

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-blog#207]
Notably the job blue link is missing.

Original li:
```
<li><a href="/jobs/" class="v5_link-alternative"><span class="v5_link__hover">Jobs <span class="highlight-text bold-text">We're Hiring!</span></span></a></li>
```
<img width="264" alt="Screen Shot 2020-04-27 at 10 11 17 PM" src="https://user-images.githubusercontent.com/4358288/80449478-1a113100-88d4-11ea-902f-04eb8b7b23d2.png">
<img width="208" alt="Screen Shot 2020-04-27 at 10 11 13 PM" src="https://user-images.githubusercontent.com/4358288/80449479-1aa9c780-88d4-11ea-9922-0495b8b4655f.png">

**Comment by ch264** [comment]
@tristandenyer We are hiring is an integration in the old www. We are now pulling in data from a data-json file, which will be an API at some point. Therefore at this moment this ticket is on hold, until the api has been implemented to pull in the We're hiring.

**Comment by ch264** [comment]
PR is in
