### ISSUE TITLE
Determine how many categories each post can have

### ISSUE THREAD

**Issue by mclausaudio** [postmanlabs/postman-blog#21]
Currently, some of our posts have more than one category.  We'll need to decide if we want each post to have a single category or multiple, similar to tags.

<img width="573" alt="Screen Shot 2020-02-13 at 1 55 18 PM" src="https://user-images.githubusercontent.com/14118422/74482087-bcd71900-4e68-11ea-93f1-59ad50321c25.png">

**Comment by ch264** [comment]
@mclausaudio I believe if a post has several categories attached to it in wordpress,  we have to show that in the blog too. If going forward this will change to 1 category, we still have to support old posts with several categories.
