### ISSUE TITLE
refactor gatsby-node

### ISSUE THREAD

**Issue by mclausaudio** [postmanlabs/postman-blog#22]
Break off create functions into separate files, clean up the file.

A good example:

https://github.com/wp-graphql/gatsby-wpgraphql-blog-example/blob/master/gatsby-node.js

https://github.com/wp-graphql/gatsby-wpgraphql-blog-example/blob/master/gatsby/createPosts.js

**Comment by ch264** [comment]
@mclausaudio really nice refractor! can we close this ticket?
