### ISSUE TITLE
Ability to add canonical tags to specific pages

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-blog#223]
Recently, we published a blog about SOAP requests: https://blog.postman.com/making-http-soap-requests-with-postman/

However, we still have two old blogs about SOAP requests + Postman that are getting a lot of traffic:
* https://blog.postman.com/postman-makes-soap-requests-too/
* https://blog.postman.com/making-soap-requests-using-postman/

To help ensure folks looking for information about making SOAP requests in Postman see the most recent blog, we'd like to add canonical tags to each of these old blogs.

The metadata for both old blogs should include:
<link rel="canonical" href="https://blog.postman.com/making-http-soap-requests-with-postman/" />

**Comment by ch264** [comment]
Tags are assigned in Wordpress.

**Comment by michaelbettendorf** [comment]
I will chat with Rebecca about this, as it is more in her wheelhouse.

**Comment by ch264** [comment]
canonical tags are being added by Rebecca in Yoast

**Comment by ch264** [comment]
PR is in

**Comment by michaelbettendorf** [comment]
@Linda-Koffman This one was handled by Rebecca, but the whole Yoast-canonical-tags thing is probably something that you should chat with her about at some point so you guys are on the same page.
