### ISSUE TITLE
seo preview bug

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-blog#261]
see image in comment

**Comment by ch264** [comment]
<img width="329" alt="Screen Shot 2020-05-04 at 4 24 00 PM" src="https://user-images.githubusercontent.com/36343528/81023663-ed09d480-8e25-11ea-8a89-5b9c0bdd349c.png">

**Comment by tristandenyer** [comment]
I think this is related in regards to the breadcrimb.
<img width="607" alt="Screen Shot 2020-05-08 at 9 00 21 AM" src="https://user-images.githubusercontent.com/4358288/81424230-7a8d4300-910a-11ea-9a56-6cf27fa8e108.png">

**Comment by ch264** [comment]
PR is in
