### ISSUE TITLE
Previous blog post doesn't load

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-blog#264]
Unsure if this was made on purpose but looking at the link provided - the page appears to be displaced. Can you please check this: https://blog.postman.com/2017/11/18/postman-makes-soap-requests-too/

It redirects from the blog: https://blog.postman.com/making-http-soap-requests-with-postman after clicking on "Previously published article". 

Screenshot:

<img width="796" alt="Screenshot 2020-05-05 at 11 19 40 AM" src="https://user-images.githubusercontent.com/47771757/81038038-563f2580-8ec2-11ea-9db7-13307b55861b.png">

Guess if the blog posts old - the link should be disabled.

**Comment by tristandenyer** [comment]
@Raj-postman That behavior is correct. We removed the dates from the URLs, so some of these old links still have the date baked into them and need to be cleaned up. Redirect is in place (was broken, fixed today), can try again.

**Comment by Raj-postman** [comment]
@tristandenyer Thank you! Confirming working as expected now  ✅
