### ISSUE TITLE
Image fails to load

### ISSUE THREAD

**Issue by Raj-postman** [postmanlabs/postman-blog#265]
The Image at the end of the blog looks missing: https://blog.postman.com/sweet-cosmic-karma-for-your-public-profile/

Screenshot:

<img width="769" alt="Screenshot 2020-05-05 at 12 03 36 PM" src="https://user-images.githubusercontent.com/47771757/81040271-a620eb00-8ec8-11ea-8001-d261a79f06b0.png">

**Comment by tristandenyer** [comment]
@Raj-postman This is loading for me. Can you try hard refreshing the page?
<img width="850" alt="Screen Shot 2020-05-05 at 2 57 00 PM" src="https://user-images.githubusercontent.com/4358288/81120028-be046900-8ee0-11ea-8e9c-3093d622365a.png">

**Comment by Raj-postman** [comment]
@tristandenyer Thank you - Its working fine now!
