### ISSUE TITLE
Title on Posts should be an H1; not H2

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-blog#266]
All titles on the index pages should be h2's, but the titles on Posts should be H1's

<img width="1546" alt="Screen Shot 2020-05-05 at 9 23 31 AM" src="https://user-images.githubusercontent.com/4358288/81090195-3869c480-8eb2-11ea-8fdd-366fc1403abe.png">

This is an SEO improvement.

**Comment by ch264** [comment]
PR is in
