### ISSUE TITLE
404 page not working

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-blog#268]
blog.postman.com/404 works fine, but anything else does not. Try https://blog.postman.com/4040404040

<img width="865" alt="Screen Shot 2020-05-05 at 2 44 42 PM" src="https://user-images.githubusercontent.com/4358288/81119440-9c56b200-8edf-11ea-9d2b-bd1b85d19e7a.png">

**Comment by ch264** [comment]
I am looking into this

**Comment by ch264** [comment]
fix in cloudfront
