### ISSUE TITLE
The wrong author is displaying for some posts

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/postman-blog#278]
Ankit Jaggi is shown as the author of posts where the original author has left the Postman organization. We should either show the correct author, or add text attributing the original author.

All of these blog posts attributed to Ankit Jaggi were written by someone else.

https://blog.postman.com/jaggi/page/1

**Comment by tristandenyer** [comment]
@loopDelicious This is something that will need to be handled by the blog content team in the Admin area. Will ping Michael about assigning / re-assigning the authors.

**Comment by michaelbettendorf** [comment]
This has been fixed; I went into WordPress and manually changed the authorship on the noted blog posts.

**Comment by michaelbettendorf** [comment]
@Linda-Koffman This issue is closed, but just wanted you to be aware of it.
