### ISSUE TITLE
[RTE] EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.

### ISSUE THREAD

**Issue by oswish** [postmanlabs/postman-blog#305]
_With latest on `develop`_, when I `npm run dev` and run the app in my browser, I get (in the console):

> EventSource's response has a MIME type ("application/json") that is not "text/event-stream". Aborting the connection.

<img width="1680" alt="EventSource-MIME-type-abort" src="https://user-images.githubusercontent.com/56083362/81879562-00aced80-9540-11ea-9a11-9ec8dfa6563a.png">

**Comment by oswish** [comment]
I also see the error on another Gatsby repository. Is the a Gatsby HMR thing?
<img width="1583" alt="www_EventSource-err" src="https://user-images.githubusercontent.com/56083362/81962607-d2bfbb80-95c8-11ea-9c11-5a41d9624c0c.png">

**Comment by ch264** [comment]
I just pulled down develop and ran locally and do not see the error. Could this come from a chrome extension or has this been fixed already?

**Comment by oswish** [comment]
I don't see it anymore either, nor do I see it in other Gatsby apps. My guess is that it can from an interim minor (Gatsby) version & they've since fixed it; closing now...

![demo-no-more-issue](https://user-images.githubusercontent.com/56083362/82238616-715f5b80-98ec-11ea-949d-b021e5e60e4f.gif)
