### ISSUE TITLE
Update social sharing image with new version

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-blog#330]
![postman-blog-social-image](https://user-images.githubusercontent.com/4358288/82714529-f5467a00-9c43-11ea-8ab1-6722dac32cf1.jpg)

**Comment by tristandenyer** [comment]
Image is in repo, just not linked correctly?

**Comment by ch264** [comment]
@tristandenyer is this the new default image for social images, if there is no image coming from yoast?
