### ISSUE TITLE
Add Twitch icon to social icons in Blog footer

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-blog#331]
Extend the social icons to include our Twitch profile: https://www.twitch.tv/getpostman

I attached their brand SVG. (We should use the same asset we used for WWW.

[twitch-brand-assets.zip](https://github.com/postmanlabs/postman-blog/files/4684473/twitch-brand-assets.zip)

**Comment by ch264** [comment]
PR is in prod
