### ISSUE TITLE
[csp] broken beta

### ISSUE THREAD

**Issue by oswish** [postmanlabs/postman-blog#368]
<img width="1680" alt="broken-beta-scp" src="https://user-images.githubusercontent.com/56083362/83692926-cae0af00-a5a9-11ea-8313-07b4117cabf1.png">

**Comment by ch264** [comment]
Gatsby umbrealla issue https://github.com/gatsbyjs/gatsby/issues/10890
Blog post on CSP implementation with Gatsby: https://dev.to/vcarl/securing-a-large-gatsby-site-with-a-csp-12f8
