### ISSUE TITLE
Hover state for Legal links is missing underline

### ISSUE THREAD

**Issue by tristandenyer** [postmanlabs/postman-blog#387]
WWW site has underline for Legal links in footer (bottom right.

Blog is missing this underline (bottom-border, actually; not a text-decoration, see footer links for example)
Should look like:
<img width="546" alt="Screen Shot 2020-06-16 at 5 27 35 PM" src="https://user-images.githubusercontent.com/4358288/84841333-dd6dd600-aff6-11ea-8df2-91049fd50306.png">

**Comment by ch264** [comment]
https://github.com/postmanlabs/postman-blog/pull/396
