### ISSUE TITLE
update wpgraphql to v.0.8.

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-blog#51]

**Comment by mclausaudio** [comment]
@ch264 After more research, turns out that 'graphql' tag bug may have been fixed in a future version, v0.6.2.  We're currently on v0.6.0 so we should update this week and see if it fixes.

**Comment by ch264** [comment]
we do not need tags and categories for Algolia as discussed in review with Tristan on Friday. This is great to know though. we definitely have to update to v 0.8.0

**Comment by ch264** [comment]
v0.8.0 is in progress. We are now on 0.7.0.
