### ISSUE TITLE
Continue reading... link goes to blog.postman, category and tags are no longer clickable

### ISSUE THREAD

**Issue by mclausaudio** [postmanlabs/postman-blog#52]
@ch264 

I just noticed the 'continue reading...' link now goes to our current blog, also the category and link tags are no longer clickable.  I wonder if this has something to do with them being nestined in a <p> tag?  Or maybe now that they are a tags?

<img width="283" alt="Screen Shot 2020-02-26 at 11 52 25 AM" src="https://user-images.githubusercontent.com/14118422/75382417-4e924d80-588f-11ea-8d3f-2dea26d66de5.png">
![Screen Shot 2020-02-26 at 11 52 35 AM](https://user-images.githubusercontent.com/14118422/75382419-505c1100-588f-11ea-93cc-431e4399b3d1.png)

**Comment by ch264** [comment]
so the continue reading goes directly to the blog because that is hard coded in wordpress. Once we have the url pointing to our AWS bucket, this will be ok.

I do not know what happened with the tags? lets sit together and investigage

**Comment by ch264** [comment]
@tristandenyer will look into changing Permalinks on Wordpress end

**Comment by tristandenyer** [comment]
@ch264 blog URLs are now sans date. The 'Continue reading' URL provided should match new app's URL structure—just ensure there is a trailing slash so no redirects on our end.

**Comment by ch264** [comment]
thank you @tristandenyer
