### ISSUE TITLE
implement testing with jest

### ISSUE THREAD

**Issue by mclausaudio** [postmanlabs/postman-blog#6]

**Comment by ch264** [comment]
testing is now available for header, footer and links. We can also test wpgraphql call but will have to build this out further once the 1st version of wpgraphql is out. So far we are missing documentation: 
- https://docs.wpgraphql.com/guides/testing/
- https://wp-graphql.gitbooks.io/wp-graphql/content/tutorials/unit-testing-your-code-that-extends-wpgraphql.html

**Comment by ch264** [comment]
For Graphql calls we could write Mocks
