### ISSUE TITLE
Algolia: index from Gatsby graphql layer?

### ISSUE THREAD

**Issue by ch264** [postmanlabs/postman-blog#62]
Can we point Algolia to Gatsby Graphql Layer?
We need to index all blog posts and not just first 100

**Comment by ch264** [comment]
This is going to be tricky and we need time to look into this

**Comment by mclausaudio** [comment]
I have an idea that I think will work, but it'll mean refactoring the way our pagination is done in gatsby-node.js.  May take 2 days if we run into issues but will mean we can get all the tags into algolia

**Comment by ch264** [comment]
awesome, lets plan more time in for this ticket and get the small ones out of the way first

**Comment by ch264** [comment]
I am going to attempt the algolia pagination

**Comment by ch264** [comment]
Algolia now indexes all pages that are being created
